"""add api_key_hash to merchants (agent auth)

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-05

Nullable, and not backfilled: existing pre-agent-auth merchants have no key,
and none is retroactively generated by this migration (a generated key would
need to be returned to the merchant somehow, which a schema migration can't
do). app/services/agent_auth.py fails closed (401) for any merchant with no
api_key_hash on record — same posture router_policy.py already takes for
pre-v1.2 merchants with no Policy row. Re-onboarding (or a future "rotate
key" endpoint) is how an existing merchant gets one.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("merchants", sa.Column("api_key_hash", sa.String(length=64), nullable=True))


def downgrade() -> None:
    op.drop_column("merchants", "api_key_hash")
